
# keywords
keywords = [
    "and\tkeyword",
    "as\tkeyword",
    "assert\tkeyword",
    "break\tkeyword",
    "continue\tkeyword",
    "del\tkeyword",
    "except\tkeyword",
    "exec\tkeyword",
    "False\tkeyword",
    "finally\tkeyword",
    "for\tkeyword",
    "in\tkeyword",
    "is\tkeyword",
    "None\tkeyword",
    "not\tkeyword",
    "or\tkeyword",
    "pass\tkeyword",
    "print\tkeyword",
    "raise\tkeyword",
    "return\tkeyword",
    "True\tkeyword",
    "try\tkeyword",
    "while\tkeyword",
    "with\tkeyword",
    "yield\tkeyword",
    "python\tkeyword"
]

# built-in functions
builtin_functions = [
    {"trigger":"__import__\t__import__(name[, globals[, locals[, fromlist[,level]]]])", "contents": "__import__(${1:name}${2:, ${3:globals}${4:, ${5:locals}${6:, ${7:fromlist}${8:, ${9:level}}}}})", "description": "__import__(name[, globals[, locals[, fromlist[,level]]]])"},
    {"trigger":"abs", "contents": "abs(${1:x})"},
    {"trigger":"all", "contents": "all(${1:iterable})"},
    {"trigger":"any", "contents": "any(${1:iterable})"},
    {"trigger":"basestring", "contents": "basestring()"},
    {"trigger":"bin", "contents": "bin(${1:x})"},
    {"trigger":"bool", "contents": "bool(${1:x})"},
    {"trigger":"bytearray\tbytearray([source[, encoding[, errors]]])", "contents": "bytearray(${1:source${2:, ${3:encoding}${4:, ${5:errors}}}})", "description": "bytearray([source[, encoding[, errors]]])"},
    {"trigger":"callable", "contents": "callable(${1:object})"},
    {"trigger":"chr", "contents": "chr(${1:i})"},
    {"trigger":"classmethod", "contents": "classmethod(${1:function})"},
    {"trigger":"cmp", "contents": "cmp(${1:x}, ${2:y})"},
    {"trigger":"compile", "contents": "compile(${1:source}, ${2:filename}, ${3:mode}${4:, ${5:flags} ${6:, ${7:dont_inherit}}})"},
    {"trigger":"complex\tcomplex([real[, imag]])", "contents": "complex(${1:real}${2:, ${3:imag}})", "description": "complex([real[, imag]])"},
    {"trigger":"delattr", "contents": "delattr(${1:object}, ${2:name})"},
    {"trigger":"dict", "contents": "dict(${1:kwargs})"},
    {"trigger":"dir", "contents": "dir(${1:object})"},
    {"trigger":"divmod", "contents": "divmod(${1:a}, ${2:b})"},
    {"trigger":"elif", "contents": "elif ${1:cond}:\n\t${2:pass}\n$0"},
    {"trigger":"else", "contents": "else:\n\t${1:pass}\n$0"},
    {"trigger":"enumerate", "contents": "enumerate(${1:sequence}${2:, start=${3:0}})"},
    {"trigger":"eval\teval(expression[, globals[, locals]])", "contents": "eval(${1:expression}${2:, ${3:globals}${4:, ${5:locals}}})", "description": "eval(expression[, globals[, locals]])"},
    {"trigger":"execfile\texecfile(filename[, globals[, locals]])", "contents": "execfile(${1:filename}${2:, ${3:globals}${4:, ${5:locals}}})", "description": "execfile(filename[, globals[, locals]])"},
    {"trigger":"file\tfile(name[, mode[, buffering]])", "contents": "file(${1:name}${2:, ${3:mode}${4:, ${5:buffering}}})", "description": "file(name[, mode[, buffering]])"},
    {"trigger":"filter", "contents": "filter(${1:function}, ${2:iterable})"},
    {"trigger":"float", "contents": "float(${1:x})"},
    {"trigger":"format\tformat(value[, format_spec])", "contents": "format(${1:value}${2:, ${3:format_spec}})", "description": "format(value[, format_spec])"},
    {"trigger": "fromimport", "contents": "from ${2:module} import ${4:submodule}${5: as ${6:alias}}"},
    {"trigger": "import", "contents": "import ${1:module}${2: as ${3:alias}}"},
    {"trigger":"frozenset", "contents": "frozenset(${1:iterable})"},
    {"trigger":"getattr\tgetattr(object, name[, default])", "contents": "getattr(${1:object}, ${2: name}${3:, ${4:default}})", "description": "getattr(object, name[, default])"},
    {"trigger":"globals", "contents": "globals()"},
    {"trigger":"hasattr", "contents": "hasattr(${1:object}, ${2:name})"},
    {"trigger":"hash", "contents": "hash(${1:object})"},
    {"trigger":"help", "contents": "help(${1:object})"},
    {"trigger":"hex", "contents": "hex(${1:x})"},
    {"trigger":"id", "contents": "id(${1:object})"},
    {"trigger":"input", "contents": "input(${1:prompt})"},
    {"trigger":"int", "contents": "int(${1:x})"},
    {"trigger":"isinstance", "contents": "isinstance(${1:object}, ${2:classinfo})"},
    {"trigger":"issubclass", "contents": "issubclass(${1:class}, ${2:classinfo})"},
    {"trigger":"iter\titer(${1:o}[, sentinel])", "contents": "iter(${1:o}${2:, ${3:sentinel}})", "description": "iter(${1:o}[, sentinel])"},
    {"trigger":"len", "contents": "len(${1:s})"},
    {"trigger":"list", "contents": "list(${1:iterable})"},
    {"trigger":"locals", "contents": "locals()"},
    {"trigger":"long", "contents": "long(${1:x})"},
    {"trigger":"map", "contents": "map(${1:function}, ${2:iterable})"},
    {"trigger":"max\tmax(iterable[, key])", "contents": "max(${1:iterable}${2:, ${3:key}})", "description": "max(iterable[, key])"},
    {"trigger":"memoryview", "contents": "memoryview(${1:obj})"},
    {"trigger":"min\tmin(iterable[, key])", "contents": "min(${1:iterable}${2:, ${3:key}})", "description": "min(iterable[, key])"},
    {"trigger":"next\tnext(iterator[, default])", "contents": "next(${1:iterator}${2:, ${3:default}})", "description": "next(iterator[, default])"},
    {"trigger":"object", "contents": "object()"},
    {"trigger":"oct", "contents": "oct(${1:x})"},
    {"trigger":"open\topen(name[, mode[, buffering]])", "contents": "open(${1:name}${2:, ${3:mode}${4:, ${5:buffering}}})", "description": "open(name[, mode[, buffering]])"},
    {"trigger":"ord", "contents": "ord(${1:c})"},
    {"trigger":"pow\tpow(x, y[, z])", "contents": "pow(${1:x}, ${2: y${3:, ${4:z}}})", "description": "pow(x, y[, z])"},
    {"trigger":"print", "contents": "print(*objects, sep=' ', end='\\n', file=sys.stdout)"},
    {"trigger":"property\tproperty([fget[, fset[, fdel[, doc]]]])", "contents": "property(${1:fget}${2:, ${3:fset}${4:, ${5:fdel}${6:, ${7:doc}}}})", "description": "property([fget[, fset[, fdel[, doc]]]])"},
    {"trigger":"range", "contents": "range(${1:stop})"},
    {"trigger":"raw_input", "contents": "raw_input(${1:prompt})"},
    {"trigger":"reduce\treduce(function, iterable[, initializer])", "contents": "reduce(${1:function}, ${2:iterable}${3:, ${4:initializer}})", "description": "reduce(function, iterable[, initializer])"},
    {"trigger":"reload", "contents": "reload(${1:module})"},
    {"trigger":"repr", "contents": "repr(${1:object})"},
    {"trigger":"reversed", "contents": "reversed(${1:seq})"},
    {"trigger":"round\tround(number[, ndigits])", "contents": "round(${1:number}${2:, ${3:ndigits}})", "description": "round(number[, ndigits])"},
    {"trigger":"set", "contents": "set(${1:iterable})"},
    {"trigger":"setattr", "contents": "setattr(${1:object}, ${2:name}, ${3:value})"},
    {"trigger":"slice", "contents": "slice(${1:start}${2:, ${3:stop}}${4:, ${5:step}})"},
    {"trigger":"sorted\tsorted(iterable[, key[, reverse[, cmp]]])", "contents": "sorted(${1:iterable}${2:, ${3:key}${4:, ${5:reverse}${6:, ${7:cmp}}}})", "description": "sorted(iterable[, key[, reverse[, cmp]]])"},
    {"trigger":"staticmethod", "contents": "staticmethod(${1:function})"},
    {"trigger":"str", "contents": "str(${1:object=''})"},
    {"trigger":"sum\tsum(iterable[, start])", "contents": "sum(${1:iterable}${2:, ${3:start}})", "description": "sum(iterable[, start])"},
    {"trigger":"super\tsuper(type[, object-or-type])", "contents": "super(${1:type}${2:, ${3:object-or-type}})", "description": "super(type[, object-or-type])"},
    {"trigger":"tuple", "contents": "tuple(${1:iterable})"},
    {"trigger":"type", "contents": "type(${1:object})"},
    {"trigger":"unichr", "contents": "unichr(${1:i})"},
    {"trigger":"unicode", "contents": "unicode(object='')"},
    {"trigger":"vars", "contents": "vars(${1:object})"},
    {"trigger":"xrange", "contents": "xrange(${1:start}${2:, ${3:stop}}${4:, ${5:step}})"},
    {"trigger":"zip", "contents": "zip(${1:iterable})"}
]

# Errors and Exceptions
exceptions = [
    {"trigger": "ArithmeticError\terror", "contents": "ArithmeticError(${1:\"${2: error}\"})"},
    {"trigger": "AssertionError\terror", "contents": "AssertionError(${1:\"${2: error}\"})"},
    {"trigger": "AttributeError\terror", "contents": "AttributeError(${1:\"${2: error}\"})"},
    {"trigger": "BaseException\texception", "contents": "BaseException(${1:\"${2: error}\"})"},
    {"trigger": "BufferError\terror", "contents": "BufferError(${1:\"${2: error}\"})"},
    {"trigger": "BytesWarning\twarning", "contents": "BytesWarning(${1:\"${2: error}\"})"},
    {"trigger": "DeprecationWarning\twarning", "contents": "DeprecationWarning(${1:\"${2: error}\"})"},
    {"trigger": "EnvironmentError\terror", "contents": "EnvironmentError(${1:\"${2: error}\"})"},
    {"trigger": "EOFError\terror", "contents": "EOFError(${1:\"${2: error}\"})"},
    {"trigger": "Exception\texception", "contents": "Exception(${1:\"${2: error}\"})"},
    {"trigger": "FloatingPointError\terror", "contents": "FloatingPointError(${1:\"${2: error}\"})"},
    {"trigger": "FutureWarning\twarning", "contents": "FutureWarning(${1:\"${2: error}\"})"},
    {"trigger": "GeneratorExit\texit", "contents": "GeneratorExit(${1:\"${2: error}\"})"},
    {"trigger": "ImportError\terror", "contents": "ImportError(${1:\"${2: error}\"})"},
    {"trigger": "ImportWarning\twarning", "contents": "ImportWarning(${1:\"${2: error}\"})"},
    {"trigger": "IndentationError\terror", "contents": "IndentationError(${1:\"${2: error}\"})"},
    {"trigger": "IndexError\terror", "contents": "IndexError(${1:\"${2: error}\"})"},
    {"trigger": "IOError\terror", "contents": "IOError(${1:\"${2: error}\"})"},
    {"trigger": "KeyboardInterrupt\t", "contents": "KeyboardInterrupt(${1:\"${2: error}\"})"},
    {"trigger": "KeyError\terror", "contents": "KeyError(${1:\"${2: error}\"})"},
    {"trigger": "LookupError\terror", "contents": "LookupError(${1:\"${2: error}\"})"},
    {"trigger": "MemoryError\terror", "contents": "MemoryError(${1:\"${2: error}\"})"},
    {"trigger": "NameError\terror", "contents": "NameError(${1:\"${2: error}\"})"},
    {"trigger": "NotImplemented\t", "contents": "NotImplemented(${1:\"${2: error}\"})"},
    {"trigger": "NotImplementedError\terror", "contents": "NotImplementedError(${1:\"${2: error}\"})"},
    {"trigger": "OSError\terror", "contents": "OSError(${1:\"${2: error}\"})"},
    {"trigger": "OverflowError\terror", "contents": "OverflowError(${1:\"${2: error}\"})"},
    {"trigger": "PendingDeprecationWarning\twarning", "contents": "PendingDeprecationWarning(${1:\"${2: error}\"})"},
    {"trigger": "ReferenceError\terror", "contents": "ReferenceError(${1:\"${2: error}\"})"},
    {"trigger": "RuntimeError\terror", "contents": "RuntimeError(${1:\"${2: error}\"})"},
    {"trigger": "RuntimeWarning\twarning", "contents": "RuntimeWarning(${1:\"${2: error}\"})"},
    {"trigger": "StandardError\terror", "contents": "StandardError(${1:\"${2: error}\"})"},
    {"trigger": "StopIteration\tstop", "contents": "StopIteration(${1:\"${2: error}\"})"},
    {"trigger": "SyntaxError\terror", "contents": "SyntaxError(${1:\"${2: error}\"})"},
    {"trigger": "SyntaxWarning\twarning", "contents": "SyntaxWarning(${1:\"${2: error}\"})"},
    {"trigger": "SystemError\terror", "contents": "SystemError(${1:\"${2: error}\"})"},
    {"trigger": "SystemExit\texit", "contents": "SystemExit(${1:\"${2: error}\"})"},
    {"trigger": "TabError\terror", "contents": "TabError(${1:\"${2: error}\"})"},
    {"trigger": "TypeError\terror", "contents": "TypeError(${1:\"${2: error}\"})"},
    {"trigger": "UnboundLocalError\terror", "contents": "UnboundLocalError(${1:\"${2: error}\"})"},
    {"trigger": "UnicodeDecodeError\terror", "contents": "UnicodeDecodeError(${1:\"${2: error}\"})"},
    {"trigger": "UnicodeEncodeError\terror", "contents": "UnicodeEncodeError(${1:\"${2: error}\"})"},
    {"trigger": "UnicodeTranslateError\terror", "contents": "UnicodeTranslateError(${1:\"${2: error}\"})"},
    {"trigger": "UnicodeWarning\twarning", "contents": "UnicodeWarning(${1:\"${2: error}\"})"},
    {"trigger": "UserWarning\twarning", "contents": "UserWarning(${1:\"${2: error}\"})"},
    {"trigger": "ValueError\terror", "contents": "ValueError(${1:\"${2: error}\"})"},
    {"trigger": "VMSError\terror", "contents": "VMSError(${1:\"${2: error}\"})"},
    {"trigger": "WindowsError\terror", "contents": "WindowsError(${1:\"${2: error}\"})"},
    {"trigger": "ZeroDivision\terror", "contents": "ZeroDivision(${1:\"${2: error}\"})"}
]

# 'Magic' Methods
magic = [
    {"trigger": "__abs__\tmagic", "contents": "__abs__"},
    {"trigger": "__add__\tmagic", "contents": "__add__"},
    {"trigger": "__and__\tmagic", "contents": "__and__"},
    {"trigger": "__bases__\tmagic", "contents": "__bases__"},
    {"trigger": "__call__\tmagic", "contents": "__call__"},
    {"trigger": "__class__\tmagic", "contents": "__class__"},
    {"trigger": "__cmp__\tmagic", "contents": "__cmp__"},
    {"trigger": "__coerce__\tmagic", "contents": "__coerce__"},
    {"trigger": "__complex__\tmagic", "contents": "__complex__"},
    {"trigger": "__contains__\tmagic", "contents": "__contains__"},
    {"trigger": "__del__\tmagic", "contents": "__del__"},
    {"trigger": "__delattr__\tmagic", "contents": "__delattr__"},
    {"trigger": "__delete__\tmagic", "contents": "__delete__"},
    {"trigger": "__delitem__\tmagic", "contents": "__delitem__"},
    {"trigger": "__delslice__\tmagic", "contents": "__delslice__"},
    {"trigger": "__dict__\tmagic", "contents": "__dict__"},
    {"trigger": "__div__\tmagic", "contents": "__div__"},
    {"trigger": "__divmod__\tmagic", "contents": "__divmod__"},
    {"trigger": "__doc__\tmagic", "contents": "__doc__"},
    {"trigger": "__enter__\tmagic", "contents": "__enter__"},
    {"trigger": "__eq__\tmagic", "contents": "__eq__"},
    {"trigger": "__exit__\tmagic", "contents": "__exit__"},
    {"trigger": "__file__\tmagic", "contents": "__file__"},
    {"trigger": "__float__\tmagic", "contents": "__float__"},
    {"trigger": "__floordiv__\tmagic", "contents": "__floordiv__"},
    {"trigger": "__func__\tmagic", "contents": "__func__"},
    {"trigger": "__future__\tmagic", "contents": "__future__"},
    {"trigger": "__ge__\tmagic", "contents": "__ge__"},
    {"trigger": "__get__\tmagic", "contents": "__get__"},
    {"trigger": "__getattr__\tmagic", "contents": "__getattr__"},
    {"trigger": "__getattribute__\tmagic", "contents": "__getattribute__"},
    {"trigger": "__getitem__\tmagic", "contents": "__getitem__"},
    {"trigger": "__getslice__\tmagic", "contents": "__getslice__"},
    {"trigger": "__gt__\tmagic", "contents": "__gt__"},
    {"trigger": "__hash__\tmagic", "contents": "__hash__"},
    {"trigger": "__hex__\tmagic", "contents": "__hex__"},
    {"trigger": "__iadd__\tmagic", "contents": "__iadd__"},
    {"trigger": "__iand__\tmagic", "contents": "__iand__"},
    {"trigger": "__idiv__\tmagic", "contents": "__idiv__"},
    {"trigger": "__ifloordiv__\tmagic", "contents": "__ifloordiv__"},
    {"trigger": "__ilshift__\tmagic", "contents": "__ilshift__"},
    {"trigger": "__imod__\tmagic", "contents": "__imod__"},
    {"trigger": "__imul__\tmagic", "contents": "__imul__"},
    {"trigger": "__index__\tmagic", "contents": "__index__"},
    {"trigger": "__init__\tmagic", "contents": "__init__"},
    {"trigger": "__instancecheck__\tmagic", "contents": "__instancecheck__"},
    {"trigger": "__int__\tmagic", "contents": "__int__"},
    {"trigger": "__invert__\tmagic", "contents": "__invert__"},
    {"trigger": "__iop__\tmagic", "contents": "__iop__"},
    {"trigger": "__ior__\tmagic", "contents": "__ior__"},
    {"trigger": "__ipow__\tmagic", "contents": "__ipow__"},
    {"trigger": "__irshift__\tmagic", "contents": "__irshift__"},
    {"trigger": "__isub__\tmagic", "contents": "__isub__"},
    {"trigger": "__iter__\tmagic", "contents": "__iter__"},
    {"trigger": "__itruediv__\tmagic", "contents": "__itruediv__"},
    {"trigger": "__ixor__\tmagic", "contents": "__ixor__"},
    {"trigger": "__le__\tmagic", "contents": "__le__"},
    {"trigger": "__len__\tmagic", "contents": "__len__"},
    {"trigger": "__long__\tmagic", "contents": "__long__"},
    {"trigger": "__lshift__\tmagic", "contents": "__lshift__"},
    {"trigger": "__lt__\tmagic", "contents": "__lt__"},
    {"trigger": "__metaclass__\tmagic", "contents": "__metaclass__"},
    {"trigger": "__mod__\tmagic", "contents": "__mod__"},
    {"trigger": "__module__\tmagic", "contents": "__module__"},
    {"trigger": "__mro__\tmagic", "contents": "__mro__"},
    {"trigger": "__mul__\tmagic", "contents": "__mul__"},
    {"trigger": "__name__\tmagic", "contents": "__name__"},
    {"trigger": "__ne__\tmagic", "contents": "__ne__"},
    {"trigger": "__neg__\tmagic", "contents": "__neg__"},
    {"trigger": "__new__\tmagic", "contents": "__new__"},
    {"trigger": "__nonzero__\tmagic", "contents": "__nonzero__"},
    {"trigger": "__oct__\tmagic", "contents": "__oct__"},
    {"trigger": "__op__\tmagic", "contents": "__op__"},
    {"trigger": "__or__\tmagic", "contents": "__or__"},
    {"trigger": "__pos__\tmagic", "contents": "__pos__"},
    {"trigger": "__pow__\tmagic", "contents": "__pow__"},
    {"trigger": "__radd__\tmagic", "contents": "__radd__"},
    {"trigger": "__rand__\tmagic", "contents": "__rand__"},
    {"trigger": "__rcmp__\tmagic", "contents": "__rcmp__"},
    {"trigger": "__rdiv__\tmagic", "contents": "__rdiv__"},
    {"trigger": "__rdivmod__\tmagic", "contents": "__rdivmod__"},
    {"trigger": "__repr__\tmagic", "contents": "__repr__"},
    {"trigger": "__reversed__\tmagic", "contents": "__reversed__"},
    {"trigger": "__rfloordiv__\tmagic", "contents": "__rfloordiv__"},
    {"trigger": "__rlshift__\tmagic", "contents": "__rlshift__"},
    {"trigger": "__rmod__\tmagic", "contents": "__rmod__"},
    {"trigger": "__rmul__\tmagic", "contents": "__rmul__"},
    {"trigger": "__rop__\tmagic", "contents": "__rop__"},
    {"trigger": "__ror__\tmagic", "contents": "__ror__"},
    {"trigger": "__rpow__\tmagic", "contents": "__rpow__"},
    {"trigger": "__rrshift__\tmagic", "contents": "__rrshift__"},
    {"trigger": "__rshift__\tmagic", "contents": "__rshift__"},
    {"trigger": "__rsub__\tmagic", "contents": "__rsub__"},
    {"trigger": "__rtruediv__\tmagic", "contents": "__rtruediv__"},
    {"trigger": "__rxor__\tmagic", "contents": "__rxor__"},
    {"trigger": "__self__\tmagic", "contents": "__self__"},
    {"trigger": "__set__\tmagic", "contents": "__set__"},
    {"trigger": "__setattr__\tmagic", "contents": "__setattr__"},
    {"trigger": "__setitem__\tmagic", "contents": "__setitem__"},
    {"trigger": "__setslice__\tmagic", "contents": "__setslice__"},
    {"trigger": "__slots__\tmagic", "contents": "__slots__"},
    {"trigger": "__str__\tmagic", "contents": "__str__"},
    {"trigger": "__sub__\tmagic", "contents": "__sub__"},
    {"trigger": "__subclasscheck__\tmagic", "contents": "__subclasscheck__"},
    {"trigger": "__truediv__\tmagic", "contents": "__truediv__"},
    {"trigger": "__unicode__\tmagic", "contents": "__unicode__"},
    {"trigger": "__weakref__\tmagic", "contents": "__weakref__"},
    {"trigger": "__xor__\tmagic", "contents": "__xor__"}
]

# Standard Library modules (2.7.3 and 3.x)
stdlib = [
    {"trigger": "2to3\tmodule", "content" : "2to3"},
    {"trigger": "__builtin__\tmodule", "content" : "__builtin__"},
    {"trigger": "__future__\tmodule", "content" : "__future__"},
    {"trigger": "__main__\tmodule", "content" : "__main__"},
    {"trigger": "_dummy_thread\tmodule", "content" : "_dummy_thread"},
    {"trigger": "_thread\tmodule", "content" : "_thread"},
    {"trigger": "_winreg\tmodule", "content" : "_winreg"},
    {"trigger": "abc\tmodule", "content" : "abc"},
    {"trigger": "aepack\tmodule", "content" : "aepack"},
    {"trigger": "aetools\tmodule", "content" : "aetools"},
    {"trigger": "aetypes\tmodule", "content" : "aetypes"},
    {"trigger": "aifc\tmodule", "content" : "aifc"},
    {"trigger": "al\tmodule", "content" : "al"},
    {"trigger": "AL\tmodule", "content" : "AL"},
    {"trigger": "anydbm\tmodule", "content" : "anydbm"},
    {"trigger": "argparse\tmodule", "content" : "argparse"},
    {"trigger": "array\tmodule", "content" : "array"},
    {"trigger": "ascii\tmodule", "content" : "ascii"},
    {"trigger": "ast\tmodule", "content" : "ast"},
    {"trigger": "asynchat\tmodule", "content" : "asynchat"},
    {"trigger": "asyncore\tmodule", "content" : "asyncore"},
    {"trigger": "atexit\tmodule", "content" : "atexit"},
    {"trigger": "audioop\tmodule", "content" : "audioop"},
    {"trigger": "autoGIL\tmodule", "content" : "autoGIL"},
    {"trigger": "base64\tmodule", "content" : "base64"},
    {"trigger": "BaseHTTPServer\tmodule", "content" : "BaseHTTPServer"},
    {"trigger": "Bastion\tmodule", "content" : "Bastion"},
    {"trigger": "bdb\tmodule", "content" : "bdb"},
    {"trigger": "binascii\tmodule", "content" : "binascii"},
    {"trigger": "binhex\tmodule", "content" : "binhex"},
    {"trigger": "bisect\tmodule", "content" : "bisect"},
    {"trigger": "bsddb\tmodule", "content" : "bsddb"},
    {"trigger": "builtins\tmodule", "content" : "builtins"},
    {"trigger": "bz2\tmodule", "content" : "bz2"},
    {"trigger": "calendar\tmodule", "content" : "calendar"},
    {"trigger": "cd\tmodule", "content" : "cd"},
    {"trigger": "cgi\tmodule", "content" : "cgi"},
    {"trigger": "CGIHTTPServer\tmodule", "content" : "CGIHTTPServer"},
    {"trigger": "cgitb\tmodule", "content" : "cgitb"},
    {"trigger": "chunk\tmodule", "content" : "chunk"},
    {"trigger": "client\tmodule", "content" : "client"},
    {"trigger": "cmath\tmodule", "content" : "cmath"},
    {"trigger": "cmd\tmodule", "content" : "cmd"},
    {"trigger": "code\tmodule", "content" : "code"},
    {"trigger": "codecs\tmodule", "content" : "codecs"},
    {"trigger": "codeop\tmodule", "content" : "codeop"},
    {"trigger": "collections\tmodule", "content" : "collections"},
    {"trigger": "ColorPicker\tmodule", "content" : "ColorPicker"},
    {"trigger": "colorsys\tmodule", "content" : "colorsys"},
    {"trigger": "commands\tmodule", "content" : "commands"},
    {"trigger": "compileall\tmodule", "content" : "compileall"},
    {"trigger": "config\tmodule", "content" : "config"},
    {"trigger": "ConfigParser\tmodule", "content" : "ConfigParser"},
    {"trigger": "configparser\tmodule", "content" : "configparser"},
    {"trigger": "contextlib\tmodule", "content" : "contextlib"},
    {"trigger": "Cookie\tmodule", "content" : "Cookie"},
    {"trigger": "cookiejar\tmodule", "content" : "cookiejar"},
    {"trigger": "cookielib\tmodule", "content" : "cookielib"},
    {"trigger": "cookies\tmodule", "content" : "cookies"},
    {"trigger": "copy\tmodule", "content" : "copy"},
    {"trigger": "copy_reg\tmodule", "content" : "copy_reg"},
    {"trigger": "copyreg\tmodule", "content" : "copyreg"},
    {"trigger": "cPickle\tmodule", "content" : "cPickle"},
    {"trigger": "crypt\tmodule", "content" : "crypt"},
    {"trigger": "cStringIO\tmodule", "content" : "cStringIO"},
    {"trigger": "csv\tmodule", "content" : "csv"},
    {"trigger": "ctypes\tmodule", "content" : "ctypes"},
    {"trigger": "curses\tmodule", "content" : "curses"},
    {"trigger": "datetime\tmodule", "content" : "datetime"},
    {"trigger": "dbhash\tmodule", "content" : "dbhash"},
    {"trigger": "dbm\tmodule", "content" : "dbm"},
    {"trigger": "decimal\tmodule", "content" : "decimal"},
    {"trigger": "DEVICE\tmodule", "content" : "DEVICE"},
    {"trigger": "difflib\tmodule", "content" : "difflib"},
    {"trigger": "dircache\tmodule", "content" : "dircache"},
    {"trigger": "dis\tmodule", "content" : "dis"},
    {"trigger": "distutils\tmodule", "content" : "distutils"},
    {"trigger": "dl\tmodule", "content" : "dl"},
    {"trigger": "doctest\tmodule", "content" : "doctest"},
    {"trigger": "DocXMLRPCServer\tmodule", "content" : "DocXMLRPCServer"},
    {"trigger": "dom\tmodule", "content" : "dom"},
    {"trigger": "dumbdbm\tmodule", "content" : "dumbdbm"},
    {"trigger": "dummy_thread\tmodule", "content" : "dummy_thread"},
    {"trigger": "dummy_threading\tmodule", "content" : "dummy_threading"},
    {"trigger": "EasyDialogs\tmodule", "content" : "EasyDialogs"},
    {"trigger": "ElementTree\tmodule", "content" : "ElementTree"},
    {"trigger": "email\tmodule", "content" : "email"},
    {"trigger": "entities\tmodule", "content" : "entities"},
    {"trigger": "errno\tmodule", "content" : "errno"},
    {"trigger": "error\tmodule", "content" : "error"},
    {"trigger": "expat\tmodule", "content" : "expat"},
    {"trigger": "faulthandler\tmodule", "content" : "faulthandler"},
    {"trigger": "fcntl\tmodule", "content" : "fcntl"},
    {"trigger": "filecmp\tmodule", "content" : "filecmp"},
    {"trigger": "fileinput\tmodule", "content" : "fileinput"},
    {"trigger": "findertools\tmodule", "content" : "findertools"},
    {"trigger": "fl\tmodule", "content" : "fl"},
    {"trigger": "FL\tmodule", "content" : "FL"},
    {"trigger": "flp\tmodule", "content" : "flp"},
    {"trigger": "fm\tmodule", "content" : "fm"},
    {"trigger": "fnmatch\tmodule", "content" : "fnmatch"},
    {"trigger": "formatter\tmodule", "content" : "formatter"},
    {"trigger": "fpectl\tmodule", "content" : "fpectl"},
    {"trigger": "fpformat\tmodule", "content" : "fpformat"},
    {"trigger": "fractions\tmodule", "content" : "fractions"},
    {"trigger": "FrameWork\tmodule", "content" : "FrameWork"},
    {"trigger": "ftplib\tmodule", "content" : "ftplib"},
    {"trigger": "functools\tmodule", "content" : "functools"},
    {"trigger": "futures\tmodule", "content" : "futures"},
    {"trigger": "gc\tmodule", "content" : "gc"},
    {"trigger": "gdbm\tmodule", "content" : "gdbm"},
    {"trigger": "gensuitemodule\tmodule", "content" : "gensuitemodule"},
    {"trigger": "getopt\tmodule", "content" : "getopt"},
    {"trigger": "getpass\tmodule", "content" : "getpass"},
    {"trigger": "gettext\tmodule", "content" : "gettext"},
    {"trigger": "gl\tmodule", "content" : "gl"},
    {"trigger": "GL\tmodule", "content" : "GL"},
    {"trigger": "glob\tmodule", "content" : "glob"},
    {"trigger": "grp\tmodule", "content" : "grp"},
    {"trigger": "gzip\tmodule", "content" : "gzip"},
    {"trigger": "handler\tmodule", "content" : "handler"},
    {"trigger": "handlers\tmodule", "content" : "handlers"},
    {"trigger": "hashlib\tmodule", "content" : "hashlib"},
    {"trigger": "heapq\tmodule", "content" : "heapq"},
    {"trigger": "hmac\tmodule", "content" : "hmac"},
    {"trigger": "hotshot\tmodule", "content" : "hotshot"},
    {"trigger": "html\tmodule", "content" : "html"},
    {"trigger": "htmlentitydefs\tmodule", "content" : "htmlentitydefs"},
    {"trigger": "htmllib\tmodule", "content" : "htmllib"},
    {"trigger": "HTMLParser\tmodule", "content" : "HTMLParser"},
    {"trigger": "http\tmodule", "content" : "http"},
    {"trigger": "httplib\tmodule", "content" : "httplib"},
    {"trigger": "ic\tmodule", "content" : "ic"},
    {"trigger": "imageop\tmodule", "content" : "imageop"},
    {"trigger": "imaplib\tmodule", "content" : "imaplib"},
    {"trigger": "imgfile\tmodule", "content" : "imgfile"},
    {"trigger": "imghdr\tmodule", "content" : "imghdr"},
    {"trigger": "imp\tmodule", "content" : "imp"},
    {"trigger": "importlib\tmodule", "content" : "importlib"},
    {"trigger": "imputil\tmodule", "content" : "imputil"},
    {"trigger": "inspect\tmodule", "content" : "inspect"},
    {"trigger": "io\tmodule", "content" : "io"},
    {"trigger": "ipaddress\tmodule", "content" : "ipaddress"},
    {"trigger": "itertools\tmodule", "content" : "itertools"},
    {"trigger": "jpeg\tmodule", "content" : "jpeg"},
    {"trigger": "json\tmodule", "content" : "json"},
    {"trigger": "keyword\tmodule", "content" : "keyword"},
    {"trigger": "linecache\tmodule", "content" : "linecache"},
    {"trigger": "locale\tmodule", "content" : "locale"},
    {"trigger": "logging\tmodule", "content" : "logging"},
    {"trigger": "lzma\tmodule", "content" : "lzma"},
    {"trigger": "MacOS\tmodule", "content" : "MacOS"},
    {"trigger": "macostools\tmodule", "content" : "macostools"},
    {"trigger": "macpath\tmodule", "content" : "macpath"},
    {"trigger": "mailbox\tmodule", "content" : "mailbox"},
    {"trigger": "mailcap\tmodule", "content" : "mailcap"},
    {"trigger": "marshal\tmodule", "content" : "marshal"},
    {"trigger": "math\tmodule", "content" : "math"},
    {"trigger": "md5\tmodule", "content" : "md5"},
    {"trigger": "mhlib\tmodule", "content" : "mhlib"},
    {"trigger": "mimetools\tmodule", "content" : "mimetools"},
    {"trigger": "mimetypes\tmodule", "content" : "mimetypes"},
    {"trigger": "MimeWriter\tmodule", "content" : "MimeWriter"},
    {"trigger": "mimify\tmodule", "content" : "mimify"},
    {"trigger": "MiniAEFrame\tmodule", "content" : "MiniAEFrame"},
    {"trigger": "minidom\tmodule", "content" : "minidom"},
    {"trigger": "mmap\tmodule", "content" : "mmap"},
    {"trigger": "mock\tmodule", "content" : "mock"},
    {"trigger": "modulefinder\tmodule", "content" : "modulefinder"},
    {"trigger": "msilib\tmodule", "content" : "msilib"},
    {"trigger": "msvcrt\tmodule", "content" : "msvcrt"},
    {"trigger": "multifile\tmodule", "content" : "multifile"},
    {"trigger": "multiprocessing\tmodule", "content" : "multiprocessing"},
    {"trigger": "mutex\tmodule", "content" : "mutex"},
    {"trigger": "netrc\tmodule", "content" : "netrc"},
    {"trigger": "new\tmodule", "content" : "new"},
    {"trigger": "nis\tmodule", "content" : "nis"},
    {"trigger": "nntplib\tmodule", "content" : "nntplib"},
    {"trigger": "numbers\tmodule", "content" : "numbers"},
    {"trigger": "operator\tmodule", "content" : "operator"},
    {"trigger": "optparse\tmodule", "content" : "optparse"},
    {"trigger": "os\tmodule", "content" : "os"},
    {"trigger": "ossaudiodev\tmodule", "content" : "ossaudiodev"},
    {"trigger": "panel\tmodule", "content" : "panel"},
    {"trigger": "parse\tmodule", "content" : "parse"},
    {"trigger": "parser\tmodule", "content" : "parser"},
    {"trigger": "path\tmodule", "content" : "path"},
    {"trigger": "pdb\tmodule", "content" : "pdb"},
    {"trigger": "pickle\tmodule", "content" : "pickle"},
    {"trigger": "pickletools\tmodule", "content" : "pickletools"},
    {"trigger": "pipes\tmodule", "content" : "pipes"},
    {"trigger": "pkgutil\tmodule", "content" : "pkgutil"},
    {"trigger": "platform\tmodule", "content" : "platform"},
    {"trigger": "plistlib\tmodule", "content" : "plistlib"},
    {"trigger": "popen2\tmodule", "content" : "popen2"},
    {"trigger": "poplib\tmodule", "content" : "poplib"},
    {"trigger": "posix\tmodule", "content" : "posix"},
    {"trigger": "posixfile\tmodule", "content" : "posixfile"},
    {"trigger": "pprint\tmodule", "content" : "pprint"},
    {"trigger": "pty\tmodule", "content" : "pty"},
    {"trigger": "pulldom\tmodule", "content" : "pulldom"},
    {"trigger": "pwd\tmodule", "content" : "pwd"},
    {"trigger": "py_compile\tmodule", "content" : "py_compile"},
    {"trigger": "pyclbr\tmodule", "content" : "pyclbr"},
    {"trigger": "pydoc\tmodule", "content" : "pydoc"},
    {"trigger": "Queue\tmodule", "content" : "Queue"},
    {"trigger": "queue\tmodule", "content" : "queue"},
    {"trigger": "quopri\tmodule", "content" : "quopri"},
    {"trigger": "random\tmodule", "content" : "random"},
    {"trigger": "re\tmodule", "content" : "re"},
    {"trigger": "readline\tmodule", "content" : "readline"},
    {"trigger": "repr\tmodule", "content" : "repr"},
    {"trigger": "reprlib\tmodule", "content" : "reprlib"},
    {"trigger": "request\tmodule", "content" : "request"},
    {"trigger": "resource\tmodule", "content" : "resource"},
    {"trigger": "response\tmodule", "content" : "response"},
    {"trigger": "rexec\tmodule", "content" : "rexec"},
    {"trigger": "rfc822\tmodule", "content" : "rfc822"},
    {"trigger": "rlcompleter\tmodule", "content" : "rlcompleter"},
    {"trigger": "robotparser\tmodule", "content" : "robotparser"},
    {"trigger": "runpy\tmodule", "content" : "runpy"},
    {"trigger": "sax\tmodule", "content" : "sax"},
    {"trigger": "saxutils\tmodule", "content" : "saxutils"},
    {"trigger": "sched\tmodule", "content" : "sched"},
    {"trigger": "ScrolledText\tmodule", "content" : "ScrolledText"},
    {"trigger": "scrolledtext\tmodule", "content" : "scrolledtext"},
    {"trigger": "select\tmodule", "content" : "select"},
    {"trigger": "server\tmodule", "content" : "server"},
    {"trigger": "sets\tmodule", "content" : "sets"},
    {"trigger": "sgmllib\tmodule", "content" : "sgmllib"},
    {"trigger": "sha\tmodule", "content" : "sha"},
    {"trigger": "shelve\tmodule", "content" : "shelve"},
    {"trigger": "shlex\tmodule", "content" : "shlex"},
    {"trigger": "shutil\tmodule", "content" : "shutil"},
    {"trigger": "signal\tmodule", "content" : "signal"},
    {"trigger": "SimpleHTTPServer\tmodule", "content" : "SimpleHTTPServer"},
    {"trigger": "SimpleXMLRPCServer\tmodule", "content" : "SimpleXMLRPCServer"},
    {"trigger": "site\tmodule", "content" : "site"},
    {"trigger": "smtpd\tmodule", "content" : "smtpd"},
    {"trigger": "smtplib\tmodule", "content" : "smtplib"},
    {"trigger": "sndhdr\tmodule", "content" : "sndhdr"},
    {"trigger": "socket\tmodule", "content" : "socket"},
    {"trigger": "SocketServer\tmodule", "content" : "SocketServer"},
    {"trigger": "socketserver\tmodule", "content" : "socketserver"},
    {"trigger": "spwd\tmodule", "content" : "spwd"},
    {"trigger": "sqlite3\tmodule", "content" : "sqlite3"},
    {"trigger": "ssl\tmodule", "content" : "ssl"},
    {"trigger": "stat\tmodule", "content" : "stat"},
    {"trigger": "statvfs\tmodule", "content" : "statvfs"},
    {"trigger": "string\tmodule", "content" : "string"},
    {"trigger": "StringIO\tmodule", "content" : "StringIO"},
    {"trigger": "stringprep\tmodule", "content" : "stringprep"},
    {"trigger": "struct\tmodule", "content" : "struct"},
    {"trigger": "subprocess\tmodule", "content" : "subprocess"},
    {"trigger": "sunau\tmodule", "content" : "sunau"},
    {"trigger": "support\tmodule", "content" : "support"},
    {"trigger": "symbol\tmodule", "content" : "symbol"},
    {"trigger": "symtable\tmodule", "content" : "symtable"},
    {"trigger": "sys\tmodule", "content" : "sys"},
    {"trigger": "sysconfig\tmodule", "content" : "sysconfig"},
    {"trigger": "syslog\tmodule", "content" : "syslog"},
    {"trigger": "tabnanny\tmodule", "content" : "tabnanny"},
    {"trigger": "tarfile\tmodule", "content" : "tarfile"},
    {"trigger": "telnetlib\tmodule", "content" : "telnetlib"},
    {"trigger": "tempfile\tmodule", "content" : "tempfile"},
    {"trigger": "termios\tmodule", "content" : "termios"},
    {"trigger": "test\tmodule", "content" : "test"},
    {"trigger": "test_support\tmodule", "content" : "test_support"},
    {"trigger": "textpad\tmodule", "content" : "textpad"},
    {"trigger": "textwrap\tmodule", "content" : "textwrap"},
    {"trigger": "thread\tmodule", "content" : "thread"},
    {"trigger": "threading\tmodule", "content" : "threading"},
    {"trigger": "time\tmodule", "content" : "time"},
    {"trigger": "timeit\tmodule", "content" : "timeit"},
    {"trigger": "Tix\tmodule", "content" : "Tix"},
    {"trigger": "tix\tmodule", "content" : "tix"},
    {"trigger": "Tkinter\tmodule", "content" : "Tkinter"},
    {"trigger": "tkinter\tmodule", "content" : "tkinter"},
    {"trigger": "token\tmodule", "content" : "token"},
    {"trigger": "tokenize\tmodule", "content" : "tokenize"},
    {"trigger": "trace\tmodule", "content" : "trace"},
    {"trigger": "traceback\tmodule", "content" : "traceback"},
    {"trigger": "ttk\tmodule", "content" : "ttk"},
    {"trigger": "tty\tmodule", "content" : "tty"},
    {"trigger": "turtle\tmodule", "content" : "turtle"},
    {"trigger": "types\tmodule", "content" : "types"},
    {"trigger": "unicodedata\tmodule", "content" : "unicodedata"},
    {"trigger": "unittest\tmodule", "content" : "unittest"},
    {"trigger": "urllib\tmodule", "content" : "urllib"},
    {"trigger": "urllib2\tmodule", "content" : "urllib2"},
    {"trigger": "urlparse\tmodule", "content" : "urlparse"},
    {"trigger": "user\tmodule", "content" : "user"},
    {"trigger": "UserDict\tmodule", "content" : "UserDict"},
    {"trigger": "UserList\tmodule", "content" : "UserList"},
    {"trigger": "UserString\tmodule", "content" : "UserString"},
    {"trigger": "uu\tmodule", "content" : "uu"},
    {"trigger": "uuid\tmodule", "content" : "uuid"},
    {"trigger": "venv\tmodule", "content" : "venv"},
    {"trigger": "warnings\tmodule", "content" : "warnings"},
    {"trigger": "wave\tmodule", "content" : "wave"},
    {"trigger": "weakref\tmodule", "content" : "weakref"},
    {"trigger": "webbrowser\tmodule", "content" : "webbrowser"},
    {"trigger": "whichdb\tmodule", "content" : "whichdb"},
    {"trigger": "winreg\tmodule", "content" : "winreg"},
    {"trigger": "winsound\tmodule", "content" : "winsound"},
    {"trigger": "wsgiref\tmodule", "content" : "wsgiref"},
    {"trigger": "xdrlib\tmodule", "content" : "xdrlib"},
    {"trigger": "xmlreader\tmodule", "content" : "xmlreader"},
    {"trigger": "xmlrpc\tmodule", "content" : "xmlrpc"},
    {"trigger": "xmlrpclib\tmodule", "content" : "xmlrpclib"},
    {"trigger": "zipfile\tmodule", "content" : "zipfile"},
    {"trigger": "zipimport\tmodule", "content" : "zipimport"},
    {"trigger": "zlib\tmodule", "content" : "zlib"}
]
